
services:
  backend:
    build:
      context: ./backend  # folder with your FastAPI Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend  # folder with your React Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
